apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: dvijay-container1
    image: nginx
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 80
