apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: dvijay-container1
    image: nginx
    livenessProbe:
      httpGet:
            path: /
            port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 80
